class MnemonicLibrary(object):
    DEFAULT_MNEMONIC = {
        "data"  : 00,
        "read"  : 10,
        "write" : 11,
        "writeA": 12,
        "load"  : 20,
        "store" : 21,
        "loadI" : 22,
        "add"   : 30,
        "sub"   : 31,
        "div"   : 32,
        "mod"   : 33,
        "mul"   : 34,
        "addI"  : 35,
        "subI"  : 36,
        "divI"  : 37,
        "modI"  : 38,
        "mulI"  : 39,
        "jmp"   : 40,
        "jl"    : 41,
        "jz"    : 42,
        "halt"  : 43,
        "clr"   : 50
    }